<#
  prune-deliverable.ps1
  Removes non-deliverable clutter from the shipped bundle.

  Scope: ZERO-RISK items only.
    Bucket A - generated runtime artifacts (git-ignored, regenerated on next run)
    Bucket B - reference docs that no code reads (no xlsx parser in the project)

  Does NOT touch framework code, tests, page objects, selectors, or data.
  Does NOT remove the orphaned `local-office` module (that needs code unwiring
  in src/fixtures/pages.fixture.ts + playwright.config.ts first - see README notes).

  Usage:
    pwsh scripts/prune-deliverable.ps1            # dry run - lists what would be deleted
    pwsh scripts/prune-deliverable.ps1 -Execute   # actually delete
#>

param(
  [switch]$Execute
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot   # project root (this script lives in scripts/)

# Paths are relative to the project root.
$targets = @(
  # --- Bucket A: generated runtime artifacts ---
  'reports',                          # allure-results, html-report, test-results (traces/screenshots/videos), diagnostics
  'logs/test-execution.log',          # runtime log
  '.auth/encore-state.json',          # saved auth/session state (regenerated by global-setup)
  '.auth/encore-state.lock-target',   # lockfile artifact

  # --- Bucket B: reference docs nothing loads at runtime ---
  'testcases'                         # QA tracker + test-case matrices (.xlsx); no xlsx parser in deps
)

$mode = if ($Execute) { 'DELETING' } else { 'DRY RUN (nothing deleted - pass -Execute to remove)' }
Write-Host "== prune-deliverable :: $mode ==`n"

$found = 0
foreach ($rel in $targets) {
  $full = Join-Path $root $rel
  if (Test-Path -LiteralPath $full) {
    $found++
    $item = Get-Item -LiteralPath $full -Force
    $kind = if ($item.PSIsContainer) { 'dir ' } else { 'file' }
    Write-Host ("  [remove] {0}  {1}" -f $kind, $rel)
    if ($Execute) {
      Remove-Item -LiteralPath $full -Recurse -Force -Confirm:$false
    }
  }
  else {
    Write-Host ("  [skip  ] not present: {0}" -f $rel) -ForegroundColor DarkGray
  }
}

Write-Host ""
if ($found -eq 0) {
  Write-Host "Nothing to remove - already clean." -ForegroundColor Green
}
elseif ($Execute) {
  Write-Host "Done. Removed $found item(s). All are regenerated on the next run (except testcases/ docs)." -ForegroundColor Green
}
else {
  Write-Host "Dry run complete: $found item(s) would be removed. Re-run with -Execute to delete." -ForegroundColor Yellow
}
